### ISSUE TITLE
No inputField defined?

### ISSUE THREAD

**Issue by donniegraham** [ideal-postcodes/address-finder-examples#27]
Hi, 

The react example seems to be missing referencing an inputField in the AddressFinder.setup method.

https://github.com/ideal-postcodes/address-finder-examples/blob/0039f3d0484f20a632adc6b5afbfe8d1cdfa7cd1/react/src/index.js#L21

**Comment by mfilip** [comment]
Hi @donniegraham question is if your implementation need it? Address Finder do not require it by default because line_1 is treated as first address input. But if needed can be specified separate with inputField in some custom form situations. If you will describe your need I will try to help you with implementation

**Comment by donniegraham** [comment]
I see, I could not get the example to work until I added a ref to the input field, e.g:
```
const inputField = React.useRef<HTMLInputElement>(null);
React.useEffect(() => {
      AddressFinder.setup({
        apiKey: <MYKEY>,
        detectCountry: false,
        defaultCountry: "GBR",
        restrictCountries: ["GBR"],
        inputField: inputField.current,
        outputFields: {
          line_1: "#line_1",
          line_2: "#line_2",
          post_town: "#post_town",
          postcode: "#postcode",
        },
        onAddressRetrieved: ({ line_1, line_2, post_town, postcode }) => {
          setClient({
            line_1: line_1,
            line_2: line_2,
            post_town: post_town,
            postcode: postcode,
          });
        },
      });
    }
  }, []);
```

**Comment by mfilip** [comment]
Interesting! What version of react you using in your project. I will try to reproduce it

**Comment by donniegraham** [comment]
> Interesting! What version of react you using in your project. I will try to reproduce it
> 

It's nextJS with react 18.2.0, sounds like it's just a me issue though so happy to close this!

Thank you for responding ☺️
